config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :lift_requests, only: [:show, :index, :new, :create,
                                   :edit, :update, :destroy] do
    resources :lifts, only: :create
  end
  resources :lifts, only: [:show, :destroy]
  put "pickup_lift" => "lifts#pickup"
  put "dropoff_lift" => "lifts#dropoff"

  resources :drivers, only: [:show, :new, :create] do
    resources :cars, only: [:new, :create]
  end
  resources :cars, only: :show
  root to: "lift_requests#index"
end

app/models/lift.rb
class Lift < ActiveRecord::Base
  include Geokit::Geocoders
  belongs_to :lift_request
  belongs_to :driver
  has_one :origin, through: :lift_request
  has_one :destination, through: :lift_request

  def pickup_time
    pickup_at.strftime("%l:%M%p")
  end

  def dropoff_time
    dropoff_at.strftime("%l:%M%p")
  end

  def calculate_distance
    self.distance = origin.distance_to(destination)
  end

  def formatted_distance
    distance.round(2)
  end

  def accepted?
    status == "accepted"
  end

  def in_progress?
    status == "in progress"
  end

  def complete?
    status == "complete"
  end

  def point_a(request)
    if self.accepted?
      loc = request.location
      { lat: loc.latitude,
        lng: loc.longitude }
    elsif self.in_progress? || self.complete?
      { lat: origin.latitude,
        lng: origin.longitude }
    end
  end

  def point_b
    if self.accepted?
      { lat: origin.latitude,
        lng: origin.longitude }
    elsif self.in_progress? || self.complete?
      { lat: destination.latitude,
        lng: destination.longitude }
    end
  end
end

app/controllers/lifts_controller.rb
class LiftsController < ApplicationController
  def show
    @lift = Lift.find(params[:id])
    @origin = @lift.point_a(request)
    @destination = @lift.point_b
  end

  def create
    @lift_request = LiftRequest.find(params[:lift_request_id])
    @lift = @lift_request.build_lift(driver: current_user.driver,
                                     status: "accepted")
    if @lift.save
      flash[:notice] = "Lift accepted"
      redirect_to lift_path(@lift)
    else
      render lift_request_path(@lift_request)
    end
  end

  def destroy
    @lift = current_user.driver.lifts.find(params[:id])
    if @lift.destroy
      flash[:notice] = "Lift cancelled"
      redirect_to lift_requests_path
    else
      render :show
    end
  end

  def pickup
    @lift = current_user.driver.lifts.find(params[:id])
    if @lift.update(status: "in progress", pickup_at: Time.zone.now)
      flash[:notice] = "Lift started"
      redirect_to lift_path(@lift)
    else
      render :show
    end
  end

  def dropoff
    @lift = current_user.driver.lifts.find(params[:id])
    @lift.calculate_distance
    if @lift.update(status: "complete", dropoff_at: Time.zone.now)
      flash[:notice] = "Lift completed"
      redirect_to lift_path(@lift)
    else
      render :show
    end
  end
end

app/views/lifts/show.html.erb
<div>
  Pick up passenger at: <%= @lift.origin.full_address %>
</div>
<p>Once you've picked up the passenger, click 'Start Lift' to begin the ride</p>
<%= link_to "Start Lift", pickup_lift_path(@lift, { id: @lift.id }), method: :put %>
<% if @lift.status == "in progress" %>
  <div>
    Picked up at: <%= @lift.pickup_time %>
  </div>
  <div>
    <%= link_to "Drop off passenger", dropoff_lift_path(@lift, { id: @lift.id }), method: :put %>
  </div>
<% end %>
<% if @lift.status == "in progress" || @lift.status == "accepted" %>
  <%= link_to "Cancel Lift", lift_path(@lift), method: :delete %>
<% end %>
<% if @lift.lift_request.user == current_user %>
  <%= link_to "Cancel Lift", lift_request_path(@lift.lift_request), method: :delete %>
<% end %>

<div>
  Their destination is: <%= @lift.destination.full_address %>
</div>
<% if @lift.status == "complete" %>
  <div>
    Dropped off at: <%= @lift.dropoff_time %>
  </div>
  <div>
    Total distance: <%= @lift.formatted_distance %> miles
  </div>
<% end %>


<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<% if @origin && @destination %>
  <script>
    var directionsDisplay = new google.maps.DirectionsRenderer();
    var directionsService = new google.maps.DirectionsService();

    function calcRoute() {
      var origin      = new google.maps.LatLng(<%= @origin[:lat] %>, <%= @origin[:lng] %>);
      var destination = new google.maps.LatLng(<%= @destination[:lat] %>, <%= @destination[:lng] %>);
      var request = {
          origin:      origin,
          destination: destination,
          travelMode:  google.maps.TravelMode.DRIVING
      };
      directionsService.route(request, function(response, status) {
        if (status == google.maps.DirectionsStatus.OK) {
          directionsDisplay.setDirections(response);
        }
      });
    }

    calcRoute();

    var handler = Gmaps.build('Google');
    handler.buildMap({ internal: {id: 'map'}}, function(){
      directionsDisplay.setMap(handler.getMap());
    });
  </script>
<% end %>