config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :lift_requests, only: [:show, :index, :new, :create,
                                   :edit, :update, :destroy] do
    resources :lifts, only: :create
  end
  resources :lifts, only: [:show, :destroy]
  put "pickup_lift" => "lifts#pickup"
  put "dropoff_lift" => "lifts#dropoff"

  resources :drivers, only: [:show, :new, :create] do
    resources :cars, only: [:new, :create]
  end
  resources :cars, only: :show
  root to: "lift_requests#index"
end

app/models/lift_request.rb
class LiftRequest < ActiveRecord::Base
  has_one :origin, dependent: :destroy
  has_one :destination, dependent: :destroy
  has_one :lift, dependent: :destroy

  belongs_to :user

  validates_associated :origin
  validates_associated :destination

  def self.active
    joins(:lift).where.not("lifts.status" => "complete")
  end
end

app/controllers/lift_requests_controller.rb
class LiftRequestsController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :index]

  def show
    @lift_request = LiftRequest.find(params[:id])
  end

  def index
    @lift_requests = LiftRequest.active
  end

  def new
    @lift_request = LiftRequest.new
  end

  def create
    @lift_request = current_user.lift_requests.build
    @lift_request.create_origin(origin_params)
    @lift_request.create_destination(destination_params)
    if @lift_request.save
      flash[:notice] = "Request created"
      redirect_to lift_request_path(@lift_request)
    else
      render :new
    end
  end

  def edit
    @lift_request = current_user.lift_requests.find(params[:id])
  end

  def update
    @lift_request = current_user.lift_requests.find(params[:id])
    @lift_request.origin.update(origin_params)
    @lift_request.destination.update(destination_params)
    if @lift_request.save
      flash[:notice] = "Request updated"
      redirect_to lift_request_path(@lift_request)
    else
      render :edit
    end
  end

  def destroy
    @lift_request = current_user.lift_requests.find(params[:id])
    if @lift_request.destroy
      flash[:notice] = "Request cancelled"
      redirect_to lift_requests_path
    else
      render :show
    end
  end

  private

  def origin_params
    params.require(:origin).permit(:longitude, :latitude,
                                   :address, :city,
                                   :state, :zip_code)
  end

  def destination_params
    params.require(:destination).permit(:longitude, :latitude,
                                        :address, :city,
                                        :state, :zip_code)
  end
end

app/views/lift_requests/_errors.html.erb
<% if @lift_request.errors.any? %>
  <% @lift_request.errors.full_messages.each do |error| %>
    <%= error %>
  <% end %>
  <% if @lift_request.origin.errors.any? %>
    <% @lift_request.origin.errors.full_messages.each do |error| %>
      <%= error %>
    <% end %>
  <% end %>
  <% if @lift_request.destination.errors.any? %>
    <% @lift_request.destination.errors.full_messages.each do |error| %>
      <%= error %>
    <% end %>
  <% end %>
<% end %>

app/views/lift_requests/_form.html.erb
<%= fields_for :origin, @lift_request.origin do |origin_form| %>
  <div>
    <%= origin_form.label :address, "Origin Address" %>
    <%= origin_form.text_field :address %>
  </div>
  <div>
    <%= origin_form.label :city, "Origin City" %>
    <%= origin_form.text_field :city %>
  </div>
  <div>
    <%= origin_form.label :state, "Origin State" %>
    <%= origin_form.text_field :state %>
  </div>
  <div>
    <%= origin_form.label :zip_code, "Origin Zip Code" %>
    <%= origin_form.text_field :zip_code %>
  </div>
<% end %>

<%= fields_for :destination, @lift_request.destination do |destination_form| %>
  <div>
    <%= destination_form.label :address, "Destination Address" %>
    <%= destination_form.text_field :address %>
  </div>
  <div>
    <%= destination_form.label :city, "Destination City" %>
    <%= destination_form.text_field :city %>
  </div>
  <div>
    <%= destination_form.label :state, "Destination State" %>
    <%= destination_form.text_field :state %>
  </div>
  <div>
    <%= destination_form.label :zip_code, "Destination Zip Code" %>
    <%= destination_form.text_field :zip_code %>
  </div>
<% end %>

app/views/lift_requests/edit.html.erb
<%= render partial: "/lift_requests/errors" %>

<%= form_for @lift_request do |f| %>
  <%= render partial: "/lift_requests/form" %>
  <%= f.submit "Update Lift Request" %>
<% end %>

app/views/lift_requests/index.html.erb
<h2>Lift Requests</h2>
<%= link_to "Request a Ride", new_lift_request_path %>

<% @lift_requests.each do |request| %>
  <div>
    From:
    <div><%= link_to "#{request.origin.address}", lift_request_path(request) %></div>
    To:
    <div><%= request.origin.address %></div>
  </div>
<% end %>

app/views/lift_requests/new.html.erb
<%= render partial: "/lift_requests/errors" %>

<%= form_for @lift_request do |f| %>
  <%= render partial: "/lift_requests/form" %>
  <%= f.submit "Request a Ride" %>
<% end %>

app/views/lift_requests/show.html.erb
<p>
  User needs a ride from:
  <div><%= @lift_request.origin.address %></div>
  <div><%= @lift_request.origin.city %>
  <%= @lift_request.origin.state %>
  <%= @lift_request.origin.zip_code %></div>
</p>
<div>Requested at: <%= @lift_request.origin.created_at %></div>
<p>
  And needs a ride to:
  <div><%= @lift_request.destination.address %></div>
  <div><%= @lift_request.destination.city %>
  <%= @lift_request.destination.state %>
  <%= @lift_request.destination.zip_code %></div>
</p>

<%= link_to "Accept Lift", lift_request_lifts_path(@lift_request), method: :post %>

<%= link_to "Edit Request", edit_lift_request_path(@lift_request) %>
<%= button_to "Cancel Request", lift_request_path(@lift_request), method: :delete %>