config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :lift_requests, only: [:show, :index, :new, :create,
                                   :edit, :update, :destroy] do
    resources :lifts, only: :create
  end
  resources :lifts, only: [:show, :destroy]
  put "pickup_lift" => "lifts#pickup"
  put "dropoff_lift" => "lifts#dropoff"

  resources :drivers, only: [:show, :new, :create] do
    resources :cars, only: [:new, :create]
  end
  resources :cars, only: :show
  root to: "lift_requests#index"
end

app/models/driver.rb
class Driver < ActiveRecord::Base
  belongs_to :user
  has_many :ratings, dependent: :destroy
  has_many :cars, dependent: :destroy
  has_many :lifts, dependent: :destroy

  validates :license_number, presence: true
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  def show
    @driver = current_user.driver
  end

  def new
    @driver = Driver.new
    @car = @driver.cars.build
  end

  def create
    @driver = current_user.build_driver(driver_params)
    @car = @driver.cars.build(car_params)
    if @driver.save && @car.save
      flash[:notice] = "Application submitted"
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def driver_params
    params.require(:driver).permit(:license_number)
  end

  def car_params
    params.require(:car).permit(:make, :model, :color, :year, :license_plate)
  end
end

app/views/drivers/new.html.erb
<% if @driver.errors.any? %>
  <% @driver.errors.full_messages.each do |msg| %>
    <%= msg %>
  <% end %>
<% end %>

<% if @car.errors.any? %>
  <% @car.errors.full_messages.each do |msg| %>
    <%= msg %>
  <% end %>
<% end %>

<%= form_for @driver do |f| %>
  <%= f.label :license_number, "Driver's License Number" %>
  <%= f.text_field :license_number %>

  <p>Enter details for your car:</p>
  <%= fields_for :car do |car_field| %>
    <%= car_field.label :make %>
    <%= car_field.text_field :make %>

    <%= car_field.label :model %>
    <%= car_field.text_field :model %>

    <%= car_field.label :year %>
    <%= car_field.text_field :year %>

    <%= car_field.label :color %>
    <%= car_field.text_field :color %>

    <%= car_field.label :license_plate, "License Plate" %>
    <%= car_field.text_field :license_plate %>
  <% end %>

  <%= f.submit "Submit" %>
<% end %>

app/views/drivers/show.html.erb
<%= link_to "Add a Car", new_driver_car_path(@driver) %>
<% @driver.cars.each do |car| %>
  <%= car.formatted_name %>
<% end %>